### ISSUE TITLE
Possible to get the *training* script for PBDRKbrain?

### ISSUE THREAD

**Issue by hegde00** [ANTsRNet/PBDRKbrain#1]
Hi Nick et al,

I was wondering if it's possible to get the training script for PBDRKbrain (i.e., the script that generated the 'PBDRKbrainModel.h5' file specified on line 46 of PBDRKbrainModelPredict.R)?

Thank you very much,
Jay

**Comment by ntustison** [comment]
I didn’t create that network so the training script is probably not available.

**Comment by hegde00** [comment]
OK Nick, thank you for letting me know.
